### ISSUE TITLE
Prebuilt APK 

### ISSUE THREAD

**Issue by jfrobbins** [szelok/twister-android#2]
There's no prebuilt apk that I've found.  It would be great if this app was in f-droid

**Comment by szelok** [comment]
good suggestion. submit a request to add
https://f-droid.org/forums/topic/android-client-for-twister/

**Comment by jfrobbins** [comment]
I don't see it in a websearch, but it did turn up in the f-droid app on my phone.  
does it still require the twister simple client to work?

**Comment by szelok** [comment]
it does not require to have the html5/js client. but it does require to have twisterd to run on another host.

in my case, i have ONLY ONE twisterd running on my mac. i am using html5/js client on mac and windows. and i am using android client on my phone and tablet.

enjoy.

**Comment by jfrobbins** [comment]
ah! understood, thanks.  

I think we should be able to close this, as it is in f-droid now
