### ISSUE TITLE
Apk ?

### ISSUE THREAD

**Issue by wilfried18** [szelok/twister-android#3]
The application is not on google play store? because of the application is incomplete fdroid 
or can I find the apk and used to test your application

**Comment by szelok** [comment]
I requested f-droid to build an apk. but nobody respond so far. any suggestion to put an apk I built?

**Comment by jfrobbins** [comment]
there's an APK in f-droid now ( #2 ).

**Comment by szelok** [comment]
fdroid link https://f-droid.org/repository/browse/?fdid=szelok.app.twister
